services:
  api:
    image: ghcr.io/oscarlopezll/archivosdocker-api:latest
    ports:
      - "8000:8000"

  shiny:
    image: ghcr.io/oscarlopezll/archivosdocker-shiny:latest
    platform: linux/amd64 
    ports:
      - "3838:3838"
    environment:
      - API_BASE=http://api:8000
    depends_on:
      - api

